version: '3'

services:
  web:
    build: .
    container_name: web 
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./Web:/Web
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:  
      - ./grafana.ini:/etc/grafana/grafana.ini
